### PR TITLE
  Merge original nginx v1.10.2, ready to launch a new SEnginx release

### PR DESCRIPTION
**Pull request by skyever**
Signed-off-by: skyever <i@kill9.cn>

### CODE REVIEW

**Comment by gsdu8g9** [comment]
./se-configure.sh --user=www-data --group=www-data
make

cc1: all warnings being treated as errors
objs/Makefile:982: recipe for target 'objs/src/http/ngx_http_upstream.o' failed
make[1]: *** [objs/src/http/ngx_http_upstream.o] Error 1
make[1]: Leaving directory '/root/SEnginx'
Makefile:8: recipe for target 'build' failed
make: *** [build] Error 2

**Comment by skyever** [comment]
@gsdu8g9 Already fix this error, you can try it again.

**Comment by gsdu8g9** [comment]
It is possible to compile now. 
Robot mitigation module works. 
I have also tested it with this additional module 
https://github.com/flant/nginx-http-rdns 
It is also works.

**Comment by InfoHunter** [comment]
@skyever pls resolve the conflicts, since I have merged some pr launched 2 years ago...

**Comment by InfoHunter** [comment]
Merged!

**Pull request merged**
